# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "025df740c8a79a0853a7939da465efb0"
application_url = "https://walking-expired-shepherd-gross.trycloudflare.com"
embedded = true
name = "voicero-app-shop-test"
handle = "voicero-app-shop-test"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/gdpr"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products,read_discounts,write_content,read_metaobjects,write_metaobjects,read_inventory,read_product_listings"

[auth]
redirect_urls = [
  "https://walking-expired-shepherd-gross.trycloudflare.com/auth/callback",
  "https://walking-expired-shepherd-gross.trycloudflare.com/auth/shopify/callback",
  "https://walking-expired-shepherd-gross.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
